name: Pull request check

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required, to be implemented." '
